version: "3.9"
services:
  app:
    container_name: shamsherahmed.in
    image: shamsherahmed:v1
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"

